name: 资金盘.js
 
on:
  push:
    branches:
      - main
  schedule:   
    - cron: '0 5 * * *'   #国际标准时间，北京时间+8，即下午1点钟
 
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
           
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '16'
          
      - name: Install Dependency       
        run: |
          npm install && npm install got && npm install tough-cookie && npm install request && npm install axios js-yaml png-js date-fns axios crypto-js ts-md5 tslib @types/node requests tough-cookie jsdom download tunnel fs ws form-data
#           node ./zjp.js  #脚本存在根目录scripts文件夹下
      - name: Run Code
        run: |
         node zjp.js
         node 1.js
 
